version: '3.8'

services:
  scloud-downloader:
    image: boolty/scloud-downloader:latest
    container_name: scloud-downloader
    ports:
      - "4554:3000"
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s